# Generated by Django 2.2.7 on 2020-03-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
