# Generated by Django 2.2.7 on 2020-03-29 16:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200329_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
